### PR TITLE
Update go-dockerclient to latest version to support ~/.docker/config.json

### LINKED ISSUE #253: Cannot deploy from private docker hub repository
Trying to deploy from a private repository I own. I've authenticated with docker and I can push/pull from it. However when running a commander deploy, I get:

```
root@power-nine:~/code/PowerNine-Delivery# commander app:deploy power-nine zombor/power-nine
Pulling image zombor/power-nine...
ERROR: error pulling image zombor/power-nine. Attempt 1: Error: image zombor/power-nine: not found
ERROR: error pulling image zombor/power-nine. Attempt 2: Error: image zombor/power-nine: not found
ERROR: error pulling image zombor/power-nine. Attempt 3: Error: image zombor/power-nine: not found
ERROR: unable to pull zombor/power-nine. Has it been released yet?
```

If I make this repository public, I'm able to deploy. I'm using Docker 1.7.0 with galaxy 0.6.0.

### PR DESCRIPTION
**Pull request by zombor**
This fixes #253 again.

### CODE REVIEW

**Comment by joeshaw** [comment]
We need to be a little bit careful about upgrading go-dockerclient, as master had a pretty serious bug that bit me a while back: https://github.com/fsouza/go-dockerclient/issues/318

We need to verify that the test program there works again.

**Comment by zombor** [comment]
Fair enough. fwiw, I'm running this branch right now and haven't seen any problems. ymmv :)

**Comment by joeshaw** [comment]
Great, good to know.  I think this is probably fine, I'll just peruse the changes since the previous fix was reverted.

The difference of `~/.docker/config` versus `~/.dockercfg` bit me too, and I had no idea what was going on at the time, so thanks for tracking this down.

**Comment by joeshaw** [comment]
Looks also like this upgrade might make https://github.com/litl/galaxy/pull/254 unnecessary: https://github.com/fsouza/go-dockerclient/commit/ea5fb66faf9aac441f625423ee11bc2ad69fcb55

**Comment by zombor** [comment]
Yes, I think `docker.NewAuthConfigurationsFromDockerCfg()` does everything for us.

**Comment by joeshaw** [comment]
Test program worked for me, things seem to be working fine.  :+1: Thanks!

**Pull request merged**
