### PR TITLE
switch app:run command to stream output from docker container

### LINKED ISSUE #260: app:run output seems to be truncated
I ran a command via commander app:run that appeared to exit without any indication of why.  Running the same command in the shell showed substantially more text, which contained an actual error message at the end.

### PR DESCRIPTION
**Pull request by joeshaw**
Fixes a problem where long-running commands did not have their output
displayed locally (although they did end up in the logs).

Fixes #260

### CODE REVIEW

**Comment by jbardin** [comment]
works for me here,  :+1:
My only concern is that `Stream` was specifically set to `false` in the code for some reason, instead of taking the default value like the other fields

**Comment by jbardin** [comment]
Ah, I bet this is why there was a magic sleep above this.

**Comment by joeshaw** [comment]
it was added in 13c8beeee60bee5033a71e32ac82d453addea07b but there was no mention of why `Stream` was set to false.

I wonder if we should also remove the sleep?

**Comment by joeshaw** [comment]
(I'm not able to reproduce the loss of output when i remove the sleep locally, and I'm trying to run quick stuff like `date`)

**Comment by jbardin** [comment]
Yeah, I would remove the sleep and comment too. I can't find any problems without it here when Stream is set to True.

**Comment by joeshaw** [comment]
ok, added a commit that removes it.

**Comment by jwilder** [comment]
It was a workaround for a race when trying to attach to a container before it was ready.  Newer go-dockerclient or docker engine has probably fixed it by now though.  I believe it would fail to get any output in some cases.

**Pull request merged**
