### PR TITLE
More refactoring

### PR DESCRIPTION
**Pull request by jbardin**
A little more cleanup to make converting to consul more manageable.

### CODE REVIEW

**Comment by jbardin** [comment]
(we should probably do a release, at least into dev, to make sure galaxy still works :flushed: )

**Comment by joeshaw** [comment]
Do you want to do it before or after this PR?

**Comment by jbardin** [comment]
After is fine. None of the refactoring so far should have altered bahavior, but so much code has changed without tests, I just want to make sure.

**Comment by joeshaw** [comment]
:+1:

**Pull request merged**
